# Generated by Django 4.2.6 on 2023-11-07 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cryptonews_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cryptonews',
            name='pub_date',
        ),
        migrations.AddField(
            model_name='cryptonews',
            name='crypto_name',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
