# Generated by Django 4.2.6 on 2023-10-13 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DJSapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchedulerStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(default='stopped', max_length=10)),
            ],
        ),
    ]
