# Generated by Django 4.2.6 on 2023-10-13 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DJSapp', '0002_schedulerstatus'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SchedulerStatus',
        ),
    ]
